services:
  - type: web
    name: genai-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn genai_app.wsgi:application"
    envVars:
      - key: GOOGLE_API_KEY
        value: your_api_key_here
