services:
  - type: web
    name: genai-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn genai_app.wsgi:application"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROK_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
